services:
  bootstrappable-builds_java_bootstrap:
    platform: linux/amd64
    build: 
      context: ./bootstrappable-builds_java_bootstrap/
      network: host
    container_name: bootstrappable-builds_java_bootstrap
    network_mode: host
    privileged: true # Required for guix in docker
  jdk_6_to_21:
    platform: linux/amd64
    build: 
      context: ./jdk_1.6_to_21/
      network: host
    container_name: jdk_6_to_21
    network_mode: host
